### ISSUE TITLE
Automatically open a repository

### ISSUE THREAD

**Issue by Thane5** [evopen/git-lock-manager#1]
It would be faster if the program could be set to open a repository directly after startup, for example it could detect wether it is run from a git folder itself and use that. Alternatively, the app could store the last accessed folder, and automatically use that the next time it opens.

**Comment by evopen** [comment]
thank you for your suggestion. But I want to keep the app simple. First, I don't think you would put this app in git folder, this is a portable application which should goes to some dir like ProgramFiles, right? And, I don't want this app shits to user's home directory or windows's register or application's dir. 

Eventually, the WebviewLoader dll will be gone. Still waiting for the upstream.

**Comment by Thane5** [comment]
But isnt the point of portable apps to use them in a non-local way, that is not tied to a computer? I've tried this exact workflow with another lock viewer (GitLit) and it worked pretty good because i dont need to tell other people how to set this thing up. The only feature you would need for that, is the ability to use windows-startup arguments (or whatever thse are called). Essentially they let you add a windows path to the link or in a batchfile, that tells the app in which folder it should run. 
https://imgur.com/a/roLsRw6

**Comment by dolsem** [comment]
Came here looking for the exact same thing as well. My use case is extending Sourctree's functionality, as it does not support LFS locks. If the app could detect a git repo from the current working directory, you could just click Terminal in Sourcetree, type something like "glm" (provided git lock manager's installation folder is in PATH), and open the window with the repo pre-selected.

**Comment by evopen** [comment]
sorry for the late response. yup too late.
impl in f336fff4fc1c9999b5d646eb91113972308b577f
